version: '3.7'
services:
    mglara:
        build: ./
        restart: unless-stopped
        volumes:
            - /opt/www:/opt/www
            - /tmp:/tmp/host
            - ./php.ini:/usr/local/etc/php/php.ini
            - /media/publico:/media/publico                
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
            - /usr/share/zoneinfo:/usr/share/zoneinfo              
        extra_hosts:
            - "host.docker.internal:host-gateway"
            - "api-mgspa-dev.mgpapelaria.com.br:host-gateway"            
        ports:
            - "9001:9000"              
