version: '3.4'
services:
    mglara:
        build:
            './.docker'
        working_dir: /opt/www/MGLara
        tty: true
        command: >
            bash -c "chmod -R a+w /opt/www/MGLara/storage
            && service nginx start
            && service php7.1-fpm start
            && /bin/bash"
        volumes:
            - ./:/opt/www/MGLara
        network_mode: host
