version: '3.5'
services:
    mglara:
        build: ./
        volumes:
            - /opt/www:/opt/www
            - /tmp:/tmp/host
            - ./php.ini:/usr/local/etc/php/php.ini
            - /media/publico:/media/publico                
        extra_hosts:
            - "host.docker.internal:host-gateway"              
        ports:
            - "9001:9000"              
