select codpessoa, fantasia, telefone1, telefone2, telefone3, emailcobranca, email, emailnfe from tblpessoa
where 
(
emailcobranca ilike '%deivismathiasinop@gmail.com.br%'
or emailcobranca ilike '%ro_giacomelli@hotamil.com%'
or emailcobranca ilike '%rhuan_vicente_araujo@cargil.com%'
or emailcobranca ilike '%crecheuniao92@hotmail.com%'
or emailcobranca ilike '%construforte.sinop@hotmail.com%'
or emailcobranca ilike '%ivonete_giachini@hotmail.com.br%'
or emailcobranca ilike '%financeiro3wdp@terra.om.br%'
or emailcobranca ilike '%olvidoria@machadonet.com.br%'
or emailcobranca ilike '%carla@groinsumosmt. com.br%'
or emailcobranca ilike '%maisvoce_importados@hotmail.com%'
or emailcobranca ilike '%jose.garces@sadia.com.br%'
or emailcobranca ilike '%cpiotosieidi@hotmail.com.br%'
or emailcobranca ilike '%sintra.postos.sinop@hotmail.com%'
or emailcobranca ilike '%charmeperfumariafinan_@hotmail.com%'
or emailcobranca ilike '%com.nsa.aparecida@gmail.com%'
or emailcobranca ilike '%contamar_recpecao@hotmail.com%'
or emailcobranca ilike '%concretossinop@concremax.com.br%'
or emailcobranca ilike '%carlosalexandre@frialto.com.br%'
or emailcobranca ilike '%nfee@frialto.com.br%'
or emailcobranca ilike '%alcimarmanuel@hotmail.com%'
or emailcobranca ilike '%grupoferro.transwood@hotmail.com.br%'
or emailcobranca ilike '%danieli@terravivaagropecuaria.com.br%'
or emailcobranca ilike '%autorizacao@saocamiloclinica.com.br%'
or emailnfe ilike '%deivismathiasinop@gmail.com.br%'
or emailnfe ilike '%ro_giacomelli@hotamil.com%'
or emailnfe ilike '%rhuan_vicente_araujo@cargil.com%'
or emailnfe ilike '%crecheuniao92@hotmail.com%'
or emailnfe ilike '%construforte.sinop@hotmail.com%'
or emailnfe ilike '%ivonete_giachini@hotmail.com.br%'
or emailnfe ilike '%financeiro3wdp@terra.om.br%'
or emailnfe ilike '%olvidoria@machadonet.com.br%'
or emailnfe ilike '%carla@groinsumosmt.com.br%'
or emailnfe ilike '%maisvoce_importados@hotmail.com%'
or emailnfe ilike '%jose.garces@sadia.com.br%'
or emailnfe ilike '%cpiotosieidi@hotmail.com.br%'
or emailnfe ilike '%sintra.postos.sinop@hotmail.com%'
or emailnfe ilike '%charmeperfumariafinan_@hotmail.com%'
or emailnfe ilike '%com.nsa.aparecida@gmail.com%'
or emailnfe ilike '%contamar_recpecao@hotmail.com%'
or emailnfe ilike '%concretossinop@concremax.com.br%'
or emailnfe ilike '%carlosalexandre@frialto.com.br%'
or emailnfe ilike '%nfee@frialto.com.br%'
or emailnfe ilike '%alcimarmanuel@hotmail.com%'
or emailnfe ilike '%grupoferro.transwood@hotmail.com.br%'
or emailnfe ilike '%danieli@terravivaagropecuaria.com.br%'
or emailnfe ilike '%autorizacao@saocamiloclinica.com.br%'
or email ilike '%deivismathiasinop@gmail.com.br%'
or email ilike '%ro_giacomelli@hotamil.com%'
or email ilike '%rhuan_vicente_araujo@cargil.com%'
or email ilike '%crecheuniao92@hotmail.com%'
or email ilike '%construforte.sinop@hotmail.com%'
or email ilike '%ivonete_giachini@hotmail.com.br%'
or email ilike '%financeiro3wdp@terra.om.br%'
or email ilike '%olvidoria@machadonet.com.br%'
or email ilike '%carla@groinsumosmt.com.br%'
or email ilike '%maisvoce_importados@hotmail.com%'
or email ilike '%jose.garces@sadia.com.br%'
or email ilike '%cpiotosieidi@hotmail.com.br%'
or email ilike '%sintra.postos.sinop@hotmail.com%'
or email ilike '%charmeperfumariafinan_@hotmail.com%'
or email ilike '%com.nsa.aparecida@gmail.com%'
or email ilike '%contamar_recpecao@hotmail.com%'
or email ilike '%concretossinop@concremax.com.br%'
or email ilike '%carlosalexandre@frialto.com.br%'
or email ilike '%nfee@frialto.com.br%'
or email ilike '%alcimarmanuel@hotmail.com%'
or email ilike '%grupoferro.transwood@hotmail.com.br%'
or email ilike '%danieli@terravivaagropecuaria.com.br%'
or email ilike '%autorizacao@saocamiloclinica.com.br%'

)